package jsoft.objects;

public class CalendarObject {//lịch
	private int calendar_id; 
	private String calendar_title; 
	private String calendar_created_date; 
	private String calendar_firstdateofweek; 
	private String calendar_firstdateofweek_lunar; 
	private String calendar_mon_1; 
	private String calendar_mon_2; 
	private String calendar_mon_3; 
	private String calendar_tue_1; 
	private String calendar_tue_2; 
	private String calendar_tue_3; 
	private String calendar_wed_1; 
	private String calendar_wed_2; 
	private String calendar_wed_3; 
	private String calendar_thu_1; 
	private String calendar_thu_2; 
	private String calendar_thu_3; 
	private String calendar_fri_1; 
	private String calendar_fri_2; 
	private String calendar_fri_3; 
	private String calendar_sat_1; 
	private String calendar_sat_2; 
	private String calendar_sat_3; 
	private String calendar_sun_1; 
	private String calendar_sun_2; 
	private String calendar_sun_3; 
	private String calendar_notes_mon; 
	private String calendar_notes_tue; 
	private String calendar_notes_wed; 
	private String calendar_notes_thu; 
	private String calendar_notes_fri; 
	private String calendar_notes_sat; 
	private String calendar_notes_sun; 
	private String calendar_notes; 
	private byte calendar_priority; 
	private String calendar_user_name; 
	private short calendar_visited;
}
